fix: add missing `run` command fix: add missing `run` command to monte_carlo example
running the example as it is given:

kedro boot --app monte_carlo_pi.app.MonteCarloApp --pipeline monte_carlo

results in:

Usage: kedro boot [OPTIONS] COMMAND [ARGS]...
Try 'kedro boot -h' for help.
Error: No such option: --app